# Generated by Django 4.2.7 on 2024-02-03 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syed', '0004_addproject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddProject',
            new_name='Project',
        ),
    ]
